### ISSUE TITLE
Release L-CiteEval on Hugging Face

### ISSUE THREAD

**Issue by NielsRogge** [ZetangForward/L-CITEEVAL#1]
Hello @ZetangForward 🤗

I'm Niels and work as ML engineer at Hugging Face. I discovered your work as it got featured in AK's daily papers: https://huggingface.co/papers/2410.02115. The paper page lets people discuss about your paper and lets them find artifacts about it (your dataset for instance) you can also claim the paper as yours which will show up on your public profile at HF.

Would you like to host the dataset on https://huggingface.co/datasets? I see it's currently present here: https://github.com/ZetangForward/L-CITEEVAL/tree/main/dataset. Hosting on Hugging Face will give you more visibility/better discoverability, and will also allow people to do:

```python
from datasets import load_dataset

dataset = load_dataset("your-hf-org/l-citeeval")
```

If you're down, leaving a guide here: [https://huggingface.co/docs/datasets/image_dataset. We also support Webdataset, useful for image/video datasets: https://huggingface.co/docs/datasets/en/loading#webdataset.](https://huggingface.co/docs/datasets/loading#json).

Besides that, there's the [dataset viewer](https://huggingface.co/docs/hub/en/datasets-viewer) which allows people to quickly explore the first few rows of the data in the browser.

After uploaded, we can also link the datasets to the paper page (read [here](https://huggingface.co/docs/hub/en/model-cards#linking-a-paper)) so people can discover your work.

What do you think?

Kind regards,

Niels

**Comment by ZetangForward** [comment]
Sure! That's cool for us.

**Comment by NielsRogge** [comment]
Thanks @ZetangForward, would it be possible to keep this issue open until it's supported? So that we can track it :)

**Comment by ZetangForward** [comment]
> Thanks @ZetangForward, would it be possible to keep this issue open until it's supported? So that we can track it :)

Hi, one of the co-authors has uploaded the datasets: https://huggingface.co/datasets/Jonaszky123/L-CiteEval
